---
- hosts: 127.0.0.1
  connection: local
  remote_user: root
  vars:
    gitPath: /git
    piGenPath: "{{ gitPath }}/pi-gen"

  tasks:
    - name: apt-dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - python3-pip

    - name: sensor-packages
      pip:
        executable: pip3
        name:
          - RPI.GPIO
          - adafruit_blinka
          - adafruit-circuitpython-ina219

    - name: patch-boot-config
      patch:
        src: "/tmp/boot-config.txt.patch"
        dest: /boot/config.txt

    - name: run-shim-installer
      command: bash -c 'cat /tmp/onoffshim.sh | bash -s -- -y'
      become: yes
      become_user: pi
