---
- hosts: 127.0.0.1
  connection: local
  remote_user: root
  vars:
    env: dev  # dev
    gitPath: /git
    piGenPath: "{{ gitPath }}/pi-gen"

  tasks:
    - name: Install Apt Dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - vim
        - python3-pip

    - name: Install Sensor Packages
      pip:
        executable: pip3
        name:
          - RPI.GPIO
          - adafruit_blinka
          - adafruit-circuitpython-ina219

    - name: Patch Boot Config
      patch:
        src: "{{ playbook_dir }}/boot-config.txt.patch"
        dest: /boot/config.txt

    - name: Patch Bluetooth Config
      patch:
        src: "{{ playbook_dir }}/bluetooth.service.patch"
        dest: /lib/systemd/system/bluetooth.service

    - name: Touch Module Blacklist
      file:
        path: /etc/modprobe.d/raspi-blacklist.conf
        state: touch
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Enable RFComm Service
      systemd:
        name: rfcomm
        enabled: yes

    - name: Enable SSH
      systemd:
        name: sshd
        enabled: yes

    - name: Reported OS Version
      command: cat /etc/os-release
      register: osinfo

    - debug: msg="{{ osinfo.stdout }}"

    - name: Run Pimoroni OnOffShim Installer
      command: bash -c 'cat /tmp/onoffshim.sh | bash -s -- -y'
      become: yes
      become_user: pi
